pathtopropa = '/home/simon/newpropa/propa/propaattenuation' #put it in a folder named propa and call the executable propaexec

vsat_fieldNames = ["LON",
                   "LAT",
                   "COUNTRY",
                   "SEA_LAND",
                   "VSAT_ID",
                   "ALT",
                   "AVAILABILITY_UP",
                   "AVAILABILITY_DN",
                   "USER_NEED",
                   "SAT_ID",
                   "TRSP_ID",
                   "PAYLOAD_ID",
                   "POS_X_ECEF",
                   "POS_Y_ECEF",
                   "POS_Z_ECEF",
                   "SAT_POS_X_ECEF",
                   "SAT_POS_Y_ECEF",
                   "SAT_POS_Z_ECEF",
                   "DIST",
                   "ELEVATION",
                   "NADIR_X_ECEF",
                   "NADIR_Y_ECEF",
                   "NADIR_Z_ECEF",
                   "NORMAL_VECT_X",
                   "NORMAL_VECT_Y",
                   "NORMAL_VECT_Z",
                   "ROLL",
                   "PITCH",
                   "YAW",
                   "AZ_SC",
                   "ELEV_SC",
                   "CENTRAL_FQ_DN",
                   "FSL_DN",
                   "POLAR",
                   "DIAMETER",
                   "EFFICIENCY",
                   "POLAR_TILT_ANGLE",
                   "PROPAG_DN",
                   "BEAM_TX_CENTER_AZ_ANT",
                   "BEAM_TX_CENTER_EL_ANT",
                   "BEAM_TX_ANT_DIAM",
                   "BEAM_TX_TYPE",
                   "MAX_GAIN_TX",
                   "BEAM_TX_THETA_3DB",
                   "SAT_GAIN_TX",
                   "IBO",
                   "AMP_SAT",
                   "OBO",
                   "SAT_EIRP", "CSIM0", "CSN0_DN", "CSI0_DN", "GPT"]

sat_fieldNames = ['SAT_ID', "NADIR_LON", "NADIR_LAT", "DISTANCE", "INCLINATION_ANGLE", "FOV_RADIUS", "FLAG_ASC_DESC",
                  "INTERF_FLAG", "ROLL",
                  "PITCH", "YAW", "PAYLOAD_ID", "NADIR_X_ECEF", "NADIR_Y_ECEF", "NADIR_Z_ECEF", "SAT_POS_X_ECEF",
                  "SAT_POS_Y_ECEF", "SAT_POS_Z_ECEF",
                  "NORMAL_VECT_X", "NORMAL_VECT_Y", "NORMAL_VECT_Z"]

trsp_fieldNames = ["FWD_RTN_FLAG", "PAYLOAD_ID", "TRSP_ID", "SYS_TEMP", "CENTRAL_FQ_UP", "BANDWIDTH", "CENTRAL_FQ_DN",
                   "AMP_SAT", "IBO", "BEAM_RX_ID",
                   "BEAM_RX_TYPE", "BEAM_RX_CENTER_AZ_ANT", "BEAM_RX_CENTER_EL_ANT", "BEAM_RX_ANT_DIAM",
                   "BEAM_RX_THETA_3DB", "BEAM_RX_EFF", "BEAM_RX_RADIUS",
                   "BEAM_TX_ID", "BEAM_TX_TYPE", "BEAM_TX_CENTER_AZ_ANT", "BEAM_TX_CENTER_EL_ANT", "BEAM_TX_ANT_DIAM",
                   "BEAM_TX_THETA_3DB",
                   "BEAM_TX_EFF", "BEAM_TX_RADIUS", "MAX_GAIN_TX"]